name: Run Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install modules
        run: npm ci  # This ensures a clean install using package-lock.json
      - name: List installed packages
        run: npm list --depth=0
      - name: Run tests
        run: npm test -- --ci
